### ISSUE TITLE
Voltage scale for individual channels

### ISSUE THREAD

**Issue by jsiegle** [jvoigts/plugin-GUI#7]
In the previous version of the LFP Viewer, clicking on individual channels showed the upper and lower bounds of the voltage range.

In the single-channel display, the voltage scale is missing from the left-hand side. Also, it would be nice to scale the single-channel display so it doesn't use the full height of the LFP Viewer. As it is now, you typically need a different voltage range for the single-channel versus the full display.

**Comment by jvoigts** [comment]
fixed in 36a580a79a2ed5956a2768120c1e4d0ec1fe7b5c
